export const UserActionType ={
    SET_CURRENT_USER:'SET_CURRENT_USER',
    EMAIL_LOGIN_START: 'EMAIL_LOGIN_START',
    GMAIL_LOGIN_START: 'GMAIL_LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE:  'LOGIN_FAILURE',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    USER_SIGN_OUT_START: 'USER_SIGN_OUT_START',
    USER_SIGN_OUT_SUCCESS: 'USER_SIGN_OUT_SUCCESS',
    USER_SIGN_OUT_FAILURE: 'USER_SIGN_OUT_FAILURE',
    END_SPINNER: 'END_SPINNER',
    USER_SIGN_UP_START: 'USER_SIGN_UP_START',
    USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
    USER_SIGN_UP_FAILURE: 'USER_SIGN_UP_FAILURE'
};